Jekyll search functionality
Flutter-Tech/fsc-documentation-theme pull request #5
Opened 2022-04-22 11:48 UTC by caquino

This pull request adds search functionality to the template using [lunrjs](https://lunrjs.com/)

All changes are guarded inside of if clauses, so unless `site_search` is set to true on `_config.yml` it should be noop.

![2022-04-22 11 56 51](https://user-images.githubusercontent.com/55999/164708761-8c18c3ab-2238-4dac-8854-3f710e81af33.gif)

2022-04-22 13:02 UTC, caquino commented on assets/js/lunr-feed.js
> +{% if site.site_search %}
@crisostomon I've encapsulated the search database with an if clause to not impact the jekyll page generation process.

2022-04-22 14:28 UTC, robtuley requested changes
Nice 🚀  -- just a couple of minor tweaks from me, but really nice neat solution.

2022-04-22 14:28 UTC, robtuley commented on assets/js/lunr-feed.js
> +    }{% if forloop.last %}{% else %}, {% endif %}{% endfor %}];
This seems a little awkward. I [googled this](https://talk.jekyllrb.com/t/loop-through-all-pages-of-the-website/6880/2), which suggests this sort of thing should work:

```
{% assign pages = site.pages | where_exp: "item", "item.title" %}
{% assign posts = site.posts %}
{% assign noPlugin = site.without-plugin %}
{% assign allPages = pages | concat: posts | concat: noPlugin %}
{% for page in allPages %}
    ... then write your logic once ...?
{% endfor %}
```

2022-04-22 14:28 UTC, robtuley commented on assets/js/lunr-feed.js
> +    console.log("init search...")
is this intentional? I don't think we console log from anywhere else

2022-04-22 15:05 UTC, caquino commented on assets/js/lunr-feed.js
> +    console.log("init search...")
that is not intentional, I'm gonna remove it.

2022-04-22 15:11 UTC, robtuley commented on assets/js/lunr-feed.js
> +    }{% if forloop.last %}{% else %}, {% endif %}{% endfor %}];
Plus random thought... wouldn't this produce invalid json if there were no posts? e.g. `{% if forloop.last %}{% else %}, {% endif %}{% endfor %}` only applies in the last of the 3 loops, which might be an empty loop etc?

2022-04-22 15:14 UTC, caquino commented on assets/js/lunr-feed.js
> +    }{% if forloop.last %}{% else %}, {% endif %}{% endfor %}];
is generates a valid empty json, I tested it. Well at least with the existing code.

2022-04-22 17:29 UTC, caquino commented on assets/js/lunr-feed.js
> +    }{% if forloop.last %}{% else %}, {% endif %}{% endfor %}];
I did rewrite this part to improve readability, it worked but it was too complex. Can you take a look on the new version?

2022-04-26 12:24 UTC, crisostomon requested changes

2022-04-26 12:24 UTC, crisostomon commented on _includes/header.html
>      <div class="flex items-center md:ml-12">
I don't think this will adjust in a responsive way when viewing on Mobile. Have you tested on Mobile view?

2022-04-26 14:04 UTC, caquino commented
@crisostomon just to avoid going blind and testing every single possible resolution, is it possible for us to check on google analytics which devices/resolutions we need to support?

2022-04-26 19:47 UTC, crisostomon commented
> @crisostomon just to avoid going blind and testing every single possible resolution, is it possible for us to check on google analytics which devices/resolutions we need to support?

You can use the [tailwind breakpoints](https://tailwindcss.com/docs/responsive-design) so that it applies different behaviours when changing screen sizes. Don't forget that tailwind uses a Mobile first approach.

2022-04-27 08:55 UTC, caquino commented
> > @crisostomon just to avoid going blind and testing every single possible resolution, is it possible for us to check on google analytics which devices/resolutions we need to support?
> 
> You can use the [tailwind breakpoints](https://tailwindcss.com/docs/responsive-design) so that it applies different behaviours when changing screen sizes and it's quite accessible to use Don't forget that tailwind uses a Mobile first approach.

I understand that you can do responsive with anything, it just a matter of effort, but I was curious about which resolutions I need to test, as I don't know if it is worth to do responsive just for the sake of it and not because our users needs it.

Actually this got me curious, should any PR sent to this repository be responsive and tested in all possible resolutions indepent of usage?

If so maybe it will be simpler for me to override the needs files on the gbp-site repo and just ignore what is not needed by our users.

2022-04-27 10:06 UTC, crisostomon commented
> > > @crisostomon just to avoid going blind and testing every single possible resolution, is it possible for us to check on google analytics which devices/resolutions we need to support?
> > 
> > 
> > You can use the [tailwind breakpoints](https://tailwindcss.com/docs/responsive-design) so that it applies different behaviours when changing screen sizes and it's quite accessible to use Don't forget that tailwind uses a Mobile first approach.
> 
> I understand that you can do responsive with anything, it just a matter of effort, but I was curious about which resolutions I need to test.
> 
> Actually this got me curious, should any PR sent to this repository be responsive and tested in all possible resolutions indepent of usage?
> 
> If so maybe it will be simpler for me to override the needed files on the gbp-site repo and just ignore what is not needed by our users, as I have no experience with tailwind/responsive options for it.
> 
> One important thing, I don't see how we will be able to fit the search counter and search box on the same line on a lower resolution screen, so either we need to remake the functionality and remove the search result counter, or we don't support resolutions smaller than a certain size.

By default, we test the responsiveness of the layout base on the defaults of the framework used, that in this case is Tailwind. Those are defined [here](https://tailwindcss.com/docs/screens).

In case of the fitting of elements in the search box, usually, I would hide the counter because is only extra information
and not mandatory for the search to work.

I'll commit some changes related to this to your repo.

2022-04-28 10:52 UTC, crisostomon approved these changes

2022-04-28 10:58 UTC, robtuley approved these changes

2022-04-28 11:22 UTC, caquino commented
Thanks for the help @crisostomon @robtuley !

2022-04-28 11:23 UTC, merged